users: {
  shape: sql_table

  uuid: uuid {constraint: PK}
  login: text {constraint: UNQ}
  password: text
  jwt: text
  createrd_at: timestamptz
  deleted: boolean
}

orders: {
  shape: sql_table

  id: text {constraint: PK}
  uid: uuid {constraint: FK}
  accrual: int
  status: text
  updated_at: timestamptz
  deleted: boolean
}

accruals: {
  shape: sql_table

  order_id: text {constraint: [PK, FK]}
  uid: uuid {constraint: FK}
  amount: int
  deleted: boolean
}

users.uuid -> orders.uid
users.uuid -> accruals.uid
orders.id -> accruals.order_id
